services:
  db:
    image: postgres:16
    container_name: postgres_prod_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend_prod_container
    environment:
      NODE_ENV: production
    ports:
      - "8000:3000"
    command: npm start
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: frontend_prod_container
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend
